name: VUnit Tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghdl/vunit:mcode
    steps:
      - name: Install git on container
        run: |
          apt update
          apt install -y git
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Gitman update
        run: gitman update
      - name: Run simulations
        run: python run.py --vivado-skip